global:
  message: Welcome to order service product environment
server:
  port: 8085
message: Hello from Order Product
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_prod
    username: root
    password: 123456
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
