spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://localhost:3306/orderdb
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
