global:
  message: Welcome to user service product environment
server:
  port: 8083
message: Hello from Product
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_prod
    username: root
    password: 123456
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
