global:
  message: Welcome to user service dev environment
server:
  port: 8082
message: Hello from Dev
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb_dev
    username: root
    password: 
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
